import Head from "next/head";
import Image from "next/image";
import {
  FaInstagram,
  FaTwitter,
  FaGithub,
  FaLinkedin,
  FaSpotify,
} from "react-icons/fa";
import { FiArrowUpRight } from "react-icons/fi";

const links = [
  {
    name: "Twitter",
    url: "https://twitter.com/jordicapellad3s",
    image: "",
    color: "bg-[#219bf0]",
  },
  // {
  //   name: "GitHub",
  //   url: "",
  //   image: "",
  //   color: "",
  // },
  // {
  //   name: "LinkedIn",
  //   url: "",
  //   image: "",
  //   color: "",
  // },
  // {
  //   name: "Instagram",
  //   url: "",
  //   image: "",
  //   color: "",
  // },
  // {
  //   name: "Personal website",
  //   url: "",
  //   image: "",
  //   color: "",
  // },
  // {
  //   name: "Spotify",
  //   url: "",
  //   image: "",
  //   color: "",
  // },
];

const Link = ({ name, url, image, color }) => {
  console.log(color);
  return (
    <div
      className={`relative ${color} w-50 h-80 border rounded-3xl flex flex-col justify-end items-start p-4`}
    >
      <span className="absolute top-0 right-0 p-5">
        <svg
          fill="none"
          stroke="currentColor"
          strokeWidth={2.5}
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
          aria-hidden="true"
          className="w-6 h-6 text-white"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M4.5 19.5l15-15m0 0H8.25m11.25 0v11.25"
          />
        </svg>
      </span>
      <h1 className="text-xl font-bold text-white">{name}</h1>
    </div>
  );
};

export default function Home({ links }) {
  return (
    <>
      <Head>
        <title>Links</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex flex-col max-w-md mx-auto text-center">
        <header className="mt-20 mb-10">
          <h1 className="text-6xl font-bold">Link tree</h1>
        </header>
        <section className="grid grid-cols-2">
          {links.map((link) => (
            <Link
              key={link.name}
              name={link.name}
              url={link.url}
              image={link.image}
              color={link.color}
            />
          ))}
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      links,
    },
  };
}
